import 'package:flutter/material.dart';
import './models/products.dart';

import './models/category.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    producto: 'Persianas de interior',
    color: Colors.teal,
  ),
  Category(
    id: 'c2',
    producto: 'Protección solar exterior',
    color: Colors.teal,
  ),
  Category(
    id: 'c3',
    producto: 'Automatización',
    color: Colors.teal,
  ),
  /*Category(
    id: 'c4',
    producto: 'Shangri-la',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    producto: 'Lohas',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    producto: 'Verticales',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    producto: 'Panel japones',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    producto: 'Enrollable exterior',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    producto: 'Toldo retráctil',
    color: Colors.pink,
  ),
/*  Category(
    id: 'c10',
    producto: 'Automatización',
    color: Colors.teal,
  ),
  Category(
    id: 'c11',
    producto: 'Cortinas',
    color: Colors.red,
  ),*/ */
];

const DUMMY_DESCRIPTION = const [
  Product(
      id: 'm1',
      categories: ['c1'],
      title: 'Persianas enrollables',
      ancho: 9.00,
      alto: 3.00,
      lienzos: 3,
      tecnologia: Tecnologia.NoAplica,
      fabricante: Fabricante.Farz,
      imageUrl: 'http://www.farz.com.mx/IMAGENES/Enro.jpg',
      //'http://www.persianasfarz.com/images/productos/enrollable/screen2000/img-white.jpg',
      decripcion: [
        'La persiana Enrollable es una persiana de enrollamiento vertical, de posición seleccionable a cualquier punto de su altura.',
        'Es ideal para todos los espacios ya que su estructura,su diseño discreto y su funcionalidad son perfectos para cualquier lugar.',
      ],
      accesorios: [
        'Tubo reforzado 38, 43, 56 o 63 mm',
        'cadena plastica o metalica',
        'Altura de control al 85%',
        'Caída de tela: Trasera o frontal',
        'Colores predeterminados de accesorios (facia, cadena plastica): Blanco, marfil, chocolate, gris o negro',
      ],
      medidas: [
        'Tubo 38 mm: 2.00m x 3.00m',
        'Tubo 43 mm: 2.80m x 4.00m',
        'Tubo 56 mm: 3.50m x 5.00m',
      ],
      modoOperacion: 'Modo manual y automatizado',
      tejido: [
        'Black-out',
        'Traslucido',
        'Wow',
        'Certificados',
      ],
      isAutomated: true,
      isManual: true,
      isBlackout: true,
      isTraslucido: true,
      isSomfy: true,
      precio: [
        'Pirita - 2.00m - \$378.00',
        'Tamina - 2.50m - \$421.00',
        'Petunia - 3.00m - \$350.00',
        'Inspiración - 2.50m - \$442.00',
        'New York - 2.75m - \$523.00',
        'Screen 2000/4000 - 2.50m - \$350.00',
        'Espiga - 2.70m - \$500.00',
        'Zircon - 2.60m - \$387.00',
        'DriftWood - 3.00m - \$655.50',
        'Screen Premium 3.00m - \$611.00',
        'Onix - 3.00m - \$521.00',
        'Arash - 2.80m - \$439.00',
        'Hemp - 2.80m - \$427.00',
        'Parsa - 2.80m - \$473.00',
        'Aram - 2.50m - \$754.00',
        'Tamina RF - 2.50m - \$575.00',
        'Carina - 2.00m - \$503.00',
      ]),
  Product(
      id: 'm2',
      categories: ['c1'],
      title: 'Persianas Sheer-elegance',
      ancho: 4.50,
      alto: 3.00,
      lienzos: 2,
      tecnologia: Tecnologia.NoAplica,
      fabricante: Fabricante.Farz,
      imageUrl: 'http://www.farz.com.mx/IMAGENES/Sheer.jpg',
      decripcion: [
        'La persiana Sheer Elegance permite el control de la luz,',
        'ya que es una persiana de enrollamiento vertical fabricada',
        'con doble tejido, uno transparente y otro translúcido.',
        'El acomodo de estos dos tejidos permite mayor entrada de luz o mayor privacidad',
      ],
      accesorios: [
        'cadena plastica o metalica',
        'Altura de cordon al 70%',
        'Cadena plastica o metalica al 150%'
            'Colores predeterminados: Blanco, marfil, chocolate, gris o negro',
      ],
      medidas: [
        'Coral y accordian: 2.80m (alto máximo)',
        'Twiny, antares, mitra, sohaila: 3.00m(alto máximo)',
        'Wood look, NetWoodLook, Hera, Linen: 3.50m(alto máximo)',
        'Regular, poseidon, Rayan: 4.50m(alto máximo)',
        'Screen Ursiya: 2.70m(alto máximo)',
        'Rayan Aridai: 2.70m (alto máximo)'
      ],
      modoOperacion: 'Modo manual y automatizado',
      tejido: [
        'Black-out',
        'Traslucido',
      ],
      isAutomated: true,
      isManual: true,
      isBlackout: true,
      isTraslucido: true,
      isSomfy: true,
      precio: [
        'Regular - 2.75m - \$529.00',
        'Woodlook - 2.75m - \$644.00',
        'Acordian - 2.75m - \$846.50',
        'Mitra - 2.75m - \$1,199.50',
        'Antares - 2.75m - \$1,112.00',
        'Rayan - 2.75m - \$936.00',
        'Coral - 2.75m - \$984.00',
        'Linen - 2.75m - \$678.50',
        'Twiny - 2.60m \$1307.50',
        'Hera - 2.78m - \$929.00',
        'Poseidon - 2.78m - \$1,059.00',
        'Net Wood Look - 2.78m - \$803.00',
        'Sohaila - 2.78m - \$977.50',
        'Screen Aridai - 2.20m - \$1,227.00',
        'Screen Ursiya - 2.20m - \$1,590.50',
      ]),
  Product(
      id: 'm3',
      categories: ['c1'],
      title: 'Persianas romanas (Plana)',
      ancho: 2.80,
      alto: 3.00,
      lienzos: 1,
      tecnologia: Tecnologia.NoAplica,
      fabricante: Fabricante.Farz,
      imageUrl: 'http://www.farz.com.mx/IMAGENES/Romama.jpg',
      //'http://www.persianasfarz.com/images/productos/romana/pirita/img-2.jpg',
      decripcion: [
        'Persiana de funcionamiento vertical, por medio de pliegues que al subir y bajar, estos se contraen o se traslapan.',
        'Cuenta con un faldón que hace que esta persiana tenga un estilo y diseño únicos.',
      ],
      accesorios: [
        'Altura de cordon al 70%',
        'Cadena plastica o metalica al 70%'
            'Colores predeterminados: Blanco, marfil, chocolate, gris o negro',
        'Oción de faldón: Si',
      ],
      medidas: [
        '2.00 x 3.00m; Revisar con asesor',
      ],
      modoOperacion: 'Modo manual y automatizado',
      tejido: [
        'Black-out',
        'Traslucido',
        'Wow',
        'Tejido',
      ],
      isAutomated: true,
      isManual: true,
      isBlackout: true,
      isTraslucido: true,
      isSomfy: true,
      precio: [
        'New York - 2.75m - \$830.00',
        'Pirita - 2.00m - \$539.00',
        'Zircon - 2.60m - \$576.00',
        'Onix - 3.00m - \$743.00',
        'Inspiracion - 2.50m - \$642.00',
        'Screen premium - 3.00m - \$850.00',
        'Screen 2000/4000 - 2.50m - \$750.00',
        'Espiga - 2.70m - N/A',
        'Petunia - 3.00m - \$617.50',
        'Tamina - 2.50m - \$666.00',
        'Driftwood - 3.00m - \$903.00',
        'Parsa - 2.80m - \$747.50',
        'Arash - 2.80m - \$743.00',
        'Hemp - 2.80m - \$727.00',
        'Aram - 2.50m - \$1,042.00',
        'Carina - 2.00m - \$974.00',
      ]),
  //AGREGAR FOTO DE ROMANA GOTA CORRESPONDIENTE//-------------------------------
  Product(
    id: 'm4',
    categories: ['c1'],
    title: 'Persianas romanas (Gota)',
    ancho: 2.80,
    alto: 3.00,
    lienzos: 1,
    tecnologia: Tecnologia.NoAplica,
    fabricante: Fabricante.Farz,
    imageUrl: 'http://www.farz.com.mx/IMAGENES/Romama.jpg',
    decripcion: [
      'Persiana de funcionamiento vertical, por medio de pliegues que al subir y bajar, estos se contraen o se traslapan.',
      'Cuenta con un faldón que hace que esta persiana tenga un estilo y diseño únicos.',
    ],
    accesorios: [
      'Altura de cordon al 70%',
      'Cadena plastica o metalica al 70%'
          'Colores predeterminados: Blanco, marfil, chocolate, gris o negro',
      'Oción de faldón: Si',
    ],
    medidas: [
      '2.00 x 3.00m; Revisar con asesor',
    ],
    modoOperacion: 'Modo manual y automatizado',
    tejido: [
      'Black-out',
      'Traslucido',
      'Wow',
      'Tejido',
    ],
    isAutomated: true,
    isManual: true,
    isBlackout: true,
    isTraslucido: true,
    isSomfy: true,
    precio: [
      'New York - 2.75m - \$1,033.00',
      'Pirita - 2.00m - \$662.00',
      'Zircon - 2.60m - \$696.00',
      'Onix - 3.00m - \$928.00',
      'Inspiracion - 2.50m - \$783.00',
      'Screen premium - 3.00m - \$1,058.00',
      'Screen 2000/4000 - 2.50m - \$810.00',
      'Espiga - 2.70m - N/A',
      'Petunia - 3.00m - \$691.00',
      'Tamina - 2.50m - \$814.00',
      'Driftwood - 3.00m - \$1,129.00',
      'Parsa - 2.80m - N/A',
      'Arash - 2.80m - N/A',
      'Hemp - 2.80m - \$870.50',
      'Aram - 2.50m - \$1,299.50',
      'Carina - 2.00m - \$1,064.00',
    ],
  ),

  Product(
    id: 'm5',
    categories: ['c1'],
    title: 'Persianas shangri-la',
    ancho: 2.80,
    alto: 3.00,
    lienzos: 1,
    tecnologia: Tecnologia.NoAplica,
    fabricante: Fabricante.Farz,
    imageUrl: 'http://www.farz.com.mx/IMAGENES/Shangrila.jpg',
    decripcion: [
      'La persiana Shangri-La permite la entrada de luz selectiva, gracias a su capacidad de perfilar la tela, ya que su funcionalidad se aprovecha al máximo de esta manera.',
      'Esta función te permite disfrutar de la claridad de un ambiente agradable o la oscuridad tranquila para un rato de paz.',
      'Se recomienda por fuera de marco.',
    ],
    accesorios: [
      'cadena plastica o metalica',
      'Altura de control al 70%',
      'Colores predeterminados: Blanco, marfil, chocolate, gris o negro',
      'No hay empate de persianas',
    ],
    medidas: ['Tubo 38 mm: 2.00m x 3.00m', 'Consulte con su asesor de ventas'],
    modoOperacion: 'Modo manual y automatizado',
    tejido: [
      'Traslucido',
    ],
    isAutomated: true,
    isManual: true,
    isBlackout: false,
    isTraslucido: true,
    isSomfy: true,
    precio: [
      'Azara 50mm - 2.60m - \$1,220.00',
      'Sadira 70mm - 2.60m - \$1,391.50',
    ],
  ),
  Product(
    id: 'm6',
    categories: ['c1'],
    title: 'Persianas Lohas',
    ancho: 2.80,
    alto: 3.00,
    lienzos: 1,
    tecnologia: Tecnologia.NoAplica,
    fabricante: Fabricante.Farz,
    imageUrl: 'http://www.farz.com.mx/IMAGENES/Lohas.jpg',
    decripcion: [
      'Persiana fina y elegante de desplazamiento lateral, disponibilidad de posicionar en cualquier punto de su carrera,',
      'con opción a perfilar la tela en cualquier punto de la persiana para permitir mayor o menor entrada de luz.',
    ],
    accesorios: [
      'Operación sistema bastón',
      'Altura bastón 1.20m'
          'Accionamientos: 1H, 2H, Centro a los lados',
      'No hay empate de persianas',
    ],
    medidas: ['4.50m x 2.80m', 'Consulte con su asesor de ventas'],
    modoOperacion: 'Modo manual y automatizado',
    tejido: [
      'Traslucido',
    ],
    isAutomated: true,
    isManual: true,
    isBlackout: false,
    isTraslucido: true,
    isSomfy: false,
    precio: [
      'Armani - 2.80m - \$1,074.00',
      'Noblesse - 3.00m - \$1,206.00',
    ],
  ),

  Product(
    id: 'm7',
    categories: ['c1'],
    title: 'Persianas verticales PVC',
    ancho: 2.80,
    alto: 3.00,
    lienzos: 1,
    tecnologia: Tecnologia.NoAplica,
    fabricante: Fabricante.Farz,
    imageUrl: 'http://www.farz.com.mx/IMAGENES/Vertical.jpg',
    decripcion: [
      'Persiana de desplazamiento lateral, disponibilidad en tela y PVC, colores atractivos y elegantes, posibilidad de perfilar las tabletas',
      'en cualquier punto de su carrera, para permitir la entrada de luz que requieras.',
    ],
    accesorios: [
      'Cadena: Plastica o metalica',
      'Cordón poliester blanco',
      'Altura mandos: 70% altura persiana',
      'Galería: portatela o redonda',
      'Cadena inferior: #3',
      'Accionamientos: 1H, 2H, Centro a los lados',
      'No hay empate de persianas',
    ],
    medidas: ['4.50m x 2.80m', 'Consulte con su asesor de ventas'],
    modoOperacion: 'Modo manual y automatizado',
    tejido: [
      'P.V.C',
      'WOW!',
    ],
    isAutomated: true,
    isManual: true,
    isBlackout: false,
    isTraslucido: true,
    isSomfy: false,
    precio: [
      'Precios c/galería portatela - c/galería redonda - Precio M/L',
      'Liso 22 - \$241.00 - \$321.00 - \$13.50',
      'Liso 27 - \$262.00 - \$343.00 - \$16.00',
      'Rayado 22 - \$278.00 - \$342.00 - \$16.00',
      'Rayado 27 - \$297.00 - \$361.00 - \$18.50',
      'Strings - \$308.00 - \$372.00 - \$20.00',
      'Sand - \$315.00 - \$381 - \$21.00',
      'Lino CX - \$405.00 - \$469.00 - \$32.00',
      'Eclipse - \$469.00 - \$534.00 - \$40.00',
      'Silky Elegance - \$481.00 - \$546.00 - \$41.00',
      'Madera premium - \$676.00 - \$740.00 - \$65.00',
      'Asteroid - \$446.00 - \$510.00 - \$37.00',
      'Elite - \$446.00 - \$510.00 - \$37.00',
      'Ice - \$446.00 - \$510.00 - \$37.00',
      'Luxor - \$446.00 - \$510.00 - \$37.00',
      'Plaster - \$446.00 - \$510.00 \$37.00',
      'Space - \$446.00 - \$510.00 - \$37.00',
      'Terra - \$446.00 - \$510.00 - \$37.00',
      'Mini 22 - \$361.00 - \$424.00 - \$19.00',
    ],
  ),
  Product(
    id: 'm8',
    categories: ['c1'],
    title: 'Persianas verticales (De tela)',
    ancho: 2.80,
    alto: 3.00,
    lienzos: 1,
    tecnologia: Tecnologia.NoAplica,
    fabricante: Fabricante.Farz,
    imageUrl: 'http://www.farz.com.mx/IMAGENES/Vertical.jpg',
    decripcion: [
      'Persiana de desplazamiento lateral, disponibilidad en tela y PVC, colores atractivos y elegantes, posibilidad de perfilar las tabletas',
      'en cualquier punto de su carrera, para permitir la entrada de luz que requieras.',
    ],
    accesorios: [
      'Cadena: Plastica o metalica',
      'Cordón poliester blanco',
      'Altura mandos: 70% altura persiana',
      'Galería: portatela o redonda',
      'Cadena inferior: #3',
      'Accionamientos: 1H, 2H, Centro a los lados',
      'No hay empate de persianas',
    ],
    medidas: ['4.50m x 2.80m', 'Consulte con su asesor de ventas'],
    modoOperacion: 'Modo manual y automatizado',
    tejido: [
      'P.V.C',
      'WOW!',
    ],
    isAutomated: true,
    isManual: true,
    isBlackout: false,
    isTraslucido: true,
    isSomfy: false,
    precio: [
      'Con galería portatela - \$374.00 ',
      'Con galería redonda - \$409.50',
      'Con portatela y galería portatela - \$607.00',
      'Con portatela y galería redonda - \$636.00',
    ],
  ),
  //AGREGAR FOTO DE PANEL LISO CORRESPONDIENTE//-------------------------------
  Product(
    id: 'm9',
    categories: ['c1'],
    title: 'Persianas Panel japonés (Liso)',
    ancho: 2.80,
    alto: 3.00,
    lienzos: 1,
    tecnologia: Tecnologia.NoAplica,
    fabricante: Fabricante.Farz,
    imageUrl: 'http://www.farz.com.mx/IMAGENES/Panel.jpg',
    decripcion: [
      'Persiana de desplazamiento lateral, diseño apto para ventanas grandes. Cuenta con disponibilidad de posicionarse',
      'en cualquier punto de su carrera. Los podemos encontrar en 3, 4 y 5 vías, liso y romanizado'
    ],
    accesorios: [
      'Opciones: Liso o romanizado',
      'Cordón poliester blanco',
      'Altura mandos: 70% altura persiana',
      'Importante: Lienzos no mayores a 1 metro',
      'Accionamientos: 1H, opción 3, 4 y 5 vías',
      'Accionamientos: 2H, opción 3, 4 y 5 vías',
      'Accionamientos: Centro a los lados, 3 y 5 vías',
      'No hay empate de persianas',
    ],
    medidas: ['4.50m x 2.80m', 'Consulte con su asesor de ventas'],
    modoOperacion: 'Modo manual y automatizado',
    tejido: [
      'Traslucido',
      'Blackout',
      'WOW!',
    ],
    isAutomated: true,
    isManual: true,
    isBlackout: true,
    isTraslucido: true,
    isSomfy: false,
    precio: [
      'New York - 2.75m - \$624.00 ',
      'Pirita - 2.00m - \$435.00',
      'Zircon - 2.60m - \$481.00',
      'Onix - 3.00m - \$562.00',
      'Inspiracion - 2.50m - \$517.50',
      'Screen premium - 3.00m - \$636.00',
      'Screen 2000/4000 - 2.50m - \$559.00',
      'Espiga - 2.70m - \$570.00',
      'Petunia - 3.00m - \$505.00',
      'Tamina - 2.50m - \$531.00',
      'DriftWood - 3.00m - \$660.00',
      'Parsa -2.80m - \$575.00',
      'Arash - 2.80m - \$569.00',
      'Hemp - 2.80m - \$559.00',
      'Aram - 2.50m - \$759.00',
      'Carina -2.00m - \$583.00',
    ],
  ),
//AGREGAR FOTO DE PANEL LISO CORRESPONDIENTE//-------------------------------
  Product(
    id: 'm10',
    categories: ['c1'],
    title: 'Persianas Panel japonés (Romaninzado)',
    ancho: 2.80,
    alto: 3.00,
    lienzos: 1,
    tecnologia: Tecnologia.NoAplica,
    fabricante: Fabricante.Farz,
    imageUrl: 'http://www.farz.com.mx/IMAGENES/Panel.jpg',
    decripcion: [
      'Persiana de desplazamiento lateral, diseño apto para ventanas grandes. Cuenta con disponibilidad de posicionarse',
      'en cualquier punto de su carrera. Los podemos encontrar en 3, 4 y 5 vías, liso y romanizado'
    ],
    accesorios: [
      'Opciones: Liso o romanizado',
      'Cordón poliester blanco',
      'Altura mandos: 70% altura persiana',
      'Importante: Lienzos no mayores a 1 metro',
      'Accionamientos: 1H, opción 3, 4 y 5 vías',
      'Accionamientos: 2H, opción 3, 4 y 5 vías',
      'Accionamientos: Centro a los lados, 3 y 5 vías',
      'No hay empate de persianas',
    ],
    medidas: ['4.50m x 2.80m', 'Consulte con su asesor de ventas'],
    modoOperacion: 'Modo manual y automatizado',
    tejido: [
      'Traslucido',
      'Blackout',
      'WOW!',
    ],
    isAutomated: true,
    isManual: true,
    isBlackout: true,
    isTraslucido: true,
    isSomfy: false,
    precio: [
      'New York - 2.75m - \$861.00 ',
      'Pirita - 2.00m - \$636.00',
      'Zircon - 2.60m - \$691.00',
      'Onix - 3.00m - \$729.00',
      'Inspiracion - 2.50m - \$735.00',
      'Screen premium - 3.00m - \$852.00',
      'Screen 2000/4000 - 2.50m - \$783.00',
      'Espiga - 2.70m - N/A',
      'Petunia - 3.00m - \$719.00',
      'Tamina - 2.50m - \$729.00',
      'DriftWood - 3.00m - \$910.00',
      'Parsa -2.80m - \$784.00',
      'Arash - 2.80m - \$765.00',
      'Hemp - 2.80m - \$753.00',
      'Aram - 2.50m - \$989.00',
      'Carina -2.00m - \$791.00',
    ],
  ),

  Product(
      id: 'm11',
      categories: ['c2'],
      title: 'Enrollable exterior',
      ancho: 5.00,
      alto: 4.00,
      lienzos: 1,
      tecnologia: Tecnologia.NoAplica,
      fabricante: Fabricante.Farz,
      imageUrl: 'http://www.farz.com.mx/IMAGENES/enrollable_conle_guia_2.png',
      decripcion: [
        'Persiana enrollable de caída vertical para espacios exteriores.'
            'Funciona para protección de la lluvia, protege contra rayos UV y viento.',
        'Cuenta con cable guía ó ganchos de sujeción.',
      ],
      accesorios: [
        'Mando: manivela o automatizados',
        'Instalación: muro o techo',
        'Facia blanca (No aplica techo frontal)',
        'Manivela 1.50m',
        'Manivela 2.00m',
        'Opción 1: Cables tensores (automatización recomendada)',
        'Opción 2: Gancho de sujeción (automatización no recomendada',
      ],
      medidas: ['5.00m x 4.00m ', 'Consulte con su asesor de ventas'],
      modoOperacion: 'Modo manual y automatizado',
      tejido: [
        'Traslucido',
      ],
      isAutomated: true,
      isManual: true,
      isBlackout: false,
      isTraslucido: true,
      isSomfy: true,
      precio: [
        'Screen 4000 - 3.00m - \$835.00',
        'Screen Ziba - 2.50m - \$1,242.00',
        'Screen Zaki - 2.50m - \$1,157.00',
        'Screen Osiris - 2.50m - \$1,143.00',
        'Vinil cristal - 2.50m - \$1,573.00',
        'Manivela 1.5m - \$185.00',
        'Manivela 2.0m - \$220.00',
        'Motor \$3,095.00',
        'Facia cubre polvo ML - \$367.00',
        'Ganchos par - \$250.00',
        'Argollas par - \$168.00',
      ]),
  Product(
      id: 'm12',
      categories: ['c2'],
      title: 'Toldo retráctil',
      ancho: 8.00,
      alto: 4.00,
      lienzos: 1,
      tecnologia: Tecnologia.NoAplica,
      fabricante: Fabricante.Farz,
      imageUrl: 'http://www.farz.com.mx/IMAGENES/toldo_retactil_con_acia.png',
      decripcion: [
        'El toldo retráctil es un sistema de protección solar que puede ser instalado en zonas residenciales, balcones, patios o restaurantes',
        'Así mismo se tiene una gama de tejidos importados que cuentan con garantía en su fabricación.',
      ],
      accesorios: [
        'Mando: manivela o automatizados',
        'Instalación: muro o techo',
        'Facia blanca (No aplica techo frontal)',
        'Manivela 1.50m',
        'Manivela 2.00m',
      ],
      medidas: [
        '8.00m x 4.00m ',
        'Consulte con su asesor de ventas',
        'para tabla de proyecciones'
      ],
      modoOperacion: 'Modo manual y automatizado',
      tejido: [
        'Traslucido',
      ],
      isAutomated: true,
      isManual: true,
      isBlackout: false,
      isTraslucido: true,
      isSomfy: true,
      precio: [
        'Consultar con su asesor la tabla de proyecciones',
      ]),

  Product(
      id: 'm13',
      categories: ['c3'],
      title: 'Motor Boris 25 ES-E',
      fabricante: Fabricante.Boris,
      imageUrl: 'http://www.farz.com.mx/IMAGENES/MOTORBORIS25ES-E.png',
      decripcion: [
        'Motor Boris de batería recargable para uso interior.',
        'Ideal para lugares con dificultad de acceso a una instalación eléctrica'
      ],
      ancho: 1.80,
      alto: 2.50,
      torque: 1.2,
      rpm: 30,
      lienzos: 1,
      tecnologia: Tecnologia.Radiofrecuencia,
      accesorios: [
        'Corona motriz 38 mm',
        'Rueda motriz 38 mm',
        'Cargador o celda solar',
      ],
      precio: [
        '1 Lienzo - \$3,576.00',
        'Celda solar (Cargador, opcional) - \$1,676.00',
        'Transformador 8.4V (Cargador, opcional) - \$529.00'
      ]),
  Product(
      id: 'm14',
      categories: ['c3'],
      title: 'Motor Boris 35 MEL',
      imageUrl: 'http://www.farz.com.mx/IMAGENES/MOTORBORIS35MEL.png',
      decripcion: [
        'Motor Boris de C.A. para uso interior.',
        'Ideal para persianas de dimensiones básicas y comunes'
      ],
      ancho: 4.50,
      alto: 3.50,
      torque: 6.0,
      rpm: 28,
      lienzos: 2,
      tecnologia: Tecnologia.Radiofrecuencia,
      fabricante: Fabricante.Boris,
      accesorios: [
        'Corona motriz 43 mm',
        'Rueda motriz 43 mm',
        'Placa estrella',
      ],
      precio: [
        '1 Lienzo - \$2,472.00',
        '2 Lienzos - \$2,576.00',
      ]),
  Product(
      id: 'm15',
      categories: ['c3'],
      title: 'Motor Boris 45 MEL',
      imageUrl: 'http://www.farz.com.mx/IMAGENES/MOTORBORIS35MEL.png',
      decripcion: [
        'Motor Boris de C.A. para uso interior.',
        'Ideal para persianas de dimensiones grandes'
      ],
      ancho: 9.0,
      alto: 3.0,
      torque: 10.0,
      rpm: 30,
      lienzos: 3,
      tecnologia: Tecnologia.Radiofrecuencia,
      fabricante: Fabricante.Boris,
      accesorios: [
        'Corona motriz 63 mm',
        'Rueda motriz 63 mm',
        'Placa estrella',
      ],
      precio: [
        '1 Lienzo - \$5,129.00',
        '2 Lienzos - \$5,750.00',
        '3 Lienzos - \$7,346.00'
      ]),
  Product(
      id: 'm16',
      categories: ['c3'],
      title: 'Control Boris 140',
      imageUrl: 'http://www.farz.com.mx/IMAGENES/boris140-02.jpg',
      decripcion: [
        'Control Boris para motores de radiofrecuencia',
        'Alcance de hasta 30 m en lugares con muros',
      ],
      tecnologia: Tecnologia.Radiofrecuencia,
      fabricante: Fabricante.Boris,
      boton: Boton.Tactil,
      accesorios: ['N/A'],
      precio: [
        '1 Canal - \$423.00',
        '2 canales - \$494.00',
        '6 canales - \$706.00',
        '16 canales - \$1,176.00',
      ]),
  Product(
      id: 'm17',
      categories: ['c3'],
      title: 'Control Boris 128-01',
      imageUrl: 'http://www.farz.com.mx/IMAGENES/boris128-01.jpg',
      decripcion: [
        'Control Boris de radiofrecuencia para motores Boris',
        'Cuenta con función de temporizador para subir o bajar sus persianas de forma automatica',
      ],
      tecnologia: Tecnologia.Radiofrecuencia,
      boton: Boton.Tactil,
      fabricante: Fabricante.Boris,
      accesorios: [
        'Base para instalación a muro (atornillada o cinta doble cara) e imanes para pegar el control'
      ],
      precio: [
        '16 canales - \$1,199.00 ',
      ]),
  Product(
      id: 'm18',
      categories: ['c3'],
      title: 'Control Boris 128-03',
      imageUrl: 'http://www.farz.com.mx/IMAGENES/boris128-03.jpg',
      decripcion: [
        'Control Boris de radiofrecuencia para motores Boris',
        'Ideal para la configuración de cortineros gracias a su facilidad de visualizar las flechas de apertura y/o cierre',
      ],
      tecnologia: Tecnologia.Radiofrecuencia,
      boton: Boton.Tactil,
      fabricante: Fabricante.Boris,
      accesorios: [
        'Base para instalación a muro (atornillada o cinta doble cara) e imanes para pegar el control'
      ],
      precio: [
        '1 canal - \$706.00 ',
      ]),

  Product(
      id: 'm19',
      categories: ['c3'],
      title: 'Control Boris 505',
      imageUrl: 'http://www.farz.com.mx/IMAGENES/boris505.jpg',
      decripcion: [
        'Control Boris para motores alámbricos',
        'Interruptor de 3 pasos para subir, bajar o detener las persianas',
      ],
      tecnologia: Tecnologia.Alambrico,
      boton: Boton.Mecanico,
      fabricante: Fabricante.Boris,
      accesorios: ['N/A'],
      precio: [
        '1 motor - \$212.00 ',
      ]),

  Product(
      id: 'm20',
      categories: ['c3'],
      title: 'Smarthome Boris',
      imageUrl: 'http://www.farz.com.mx/IMAGENES/SISTEMAINTELIGENTEBORIS1.png',
      decripcion: [
        'Sistema inteligente para persianas motorizadas Boris',
        'Controle sus persianas, cortinas y toldos desde sus dispositivos móviles o por medio de comandos de voz a través de Alexa, Google Home o Siri',
      ],
      tecnologia: Tecnologia.Radiofrecuencia,
      boton: Boton.Mecanico,
      fabricante: Fabricante.Boris,
      accesorios: ['N/A'],
      precio: [
        '1 pieza - \$794.00 ',
      ]),

  Product(
      id: 'm21',
      categories: ['c3'],
      title: 'Interfaz Universal Boris',
      imageUrl: 'http://www.farz.com.mx/IMAGENES/interfazuniversa.jpg',
      decripcion: [
        'Interfaz universal para persianas motorizadas Boris',
        'Integre sus dispositivos motorizados Boris de radiofrecuencia a sistemas inteligentes a través del protocolo serial RS485, por medio de comandos en hexádecimal',
      ],
      tecnologia: Tecnologia.Radiofrecuencia,
      boton: Boton.Mecanico,
      fabricante: Fabricante.Boris,
      accesorios: [
        'Convertidor USB / RS485 - \$1,235.00',
        'Antena (incluida)',
        'Transformador de corriente (incluido)',
      ],
      precio: [
        '16 canales - \$4,116.00 ',
      ]),
];
